import os
from datetime import datetime

import numpy as np


# Edit these two values for a single manual run.  The batch runner overrides them
# in its child processes without modifying this file.
CASE3_ROUTING_MODE = "centralized"  # "centralized" or "distributed"
CASE3_RANDOM_SEED = 20260811
CASE3_ROUTING_MODE = os.environ.get(
    "EASYSATSIM_CASE3_ROUTING_MODE", CASE3_ROUTING_MODE
).strip().lower()
CASE3_RANDOM_SEED = int(
    os.environ.get("EASYSATSIM_CASE3_RANDOM_SEED", CASE3_RANDOM_SEED)
)
CASE3_OUTPUT_TIMESTAMP = os.environ.get(
    "EASYSATSIM_CASE3_OUTPUT_TIMESTAMP",
    datetime.now().strftime("%Y%m%d_%H%M%S"),
)
CASE3_OUTPUT_PREFIX = f"{CASE3_ROUTING_MODE}_seed_{CASE3_RANDOM_SEED}"
OUTPUT_PREFIX = CASE3_OUTPUT_PREFIX


# Constellation parameters: quarter-Starlink Walker-Delta scene.
ORBIT_NUMBER = 16
SATELLITE_NUMBER_PRE_ORBIT = 25
ORBIT_INCLINATION = 53
ORBIT_HEIGHT = 1150
ORBIT_OMEGA = 0


# Case 3 user and traffic parameters.
USER_NUMBER = 200
CASE3_PAIR_COUNT = 100
CASE3_GROUP_A_START_ID = 0
CASE3_GROUP_B_START_ID = CASE3_GROUP_A_START_ID + CASE3_PAIR_COUNT
CASE3_APPLICATION_PORT = 18080
CASE3_TRAFFIC_START_TIME = 5.0
CASE3_CONTROLLED_BEHAVIOR_INTERVAL = 0.2
CASE3_CONTROLLED_SEND_PERIOD = 2.0
CASE3_CONTROLLED_STAGGER_SLOT_COUNT = 50
CASE3_CONTROLLED_PACKET_SIZE_BYTE = 1200
CASE3_MESSAGE_CHAR_COUNT = 24
CASE_SIMULATION_END_TIME = 200
CASE3_FAILED_SATELLITE_ID = 377
CASE3_FAILURE_TIME = 105.0
CASE3_CENTRALIZED_ROUTE_REFRESH_INTERVAL = 50.0
CASE3_FAILURE_BEHAVIOR_INTERVAL = 0.2


# Satellite parameters.
BUFFER_MAX_BYTE = 1e20
SATELLITE_ROUTING_UPDATE_TIME = 5
SATELLITE_NEIGHBOR_UPDATE_TIME = 1
MAX_NEIGHBOR_UPDATE_TIME = 10


# User parameters.
USER_LATITUDE_MIN = -60
USER_LATITUDE_MAX = 60
USER_DATA_RATE_MIN = 10
USER_DATA_RATE_MAX = 15
DATA_SCALING = 100
USER_ROUTING_UPDATE_TIME = 9999


# Computation parameters.
LINK_TRANSMIT_RATE = 1e7
SERVICE_RATE = 1e7
PROCESSING_TIME = 1


# Physical-layer approximation parameters.
# Case 3 keeps the physical-layer approximation enabled while using a moderately
# stronger case-local link budget for the sparse 16 x 25 constellation.
PHYSICAL_LAYER_ENABLE = True
PHYSICAL_LAYER_ENABLE_DOPPLER = True
PHYSICAL_LAYER_ENABLE_DYNAMIC_RATE = True
PHYSICAL_LAYER_UPDATE_INTERVAL = 0.5
PHYSICAL_LAYER_USE_CACHE = True
PHYSICAL_LAYER_DEFAULT_PROCESSING_TIME = PROCESSING_TIME


# ISL physical-layer parameters.
ISL_CARRIER_FREQUENCY_HZ = 23e9
ISL_BANDWIDTH_HZ = 150e6
ISL_TX_POWER_DBM = 37.0
ISL_TX_ANTENNA_GAIN_DBI = 38.0
ISL_RX_ANTENNA_GAIN_DBI = 38.0
ISL_SYSTEM_LOSS_DB = 3.0
ISL_ATMOSPHERIC_LOSS_DB = 0.5
ISL_NOISE_FIGURE_DB = 3.0
ISL_MIN_SNR_DB = -5.0
ISL_MAX_DISTANCE_M = 6000000.0
ISL_DOPPLER_COMPENSATION_HZ = 1500000.0
ISL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.001
ISL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
ISL_MIN_EFFECTIVE_RATE_BPS = 1e5
ISL_SPECTRAL_EFFICIENCY = 0.65
ISL_RATE_MAPPING_MODE = "discrete"
ISL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
ISL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
    (25.0, 2e8),
)


# SGL physical-layer parameters.
SGL_CARRIER_FREQUENCY_HZ = 14e9
SGL_BANDWIDTH_HZ = 100e6
SGL_TX_POWER_DBM = 42.0
SGL_TX_ANTENNA_GAIN_DBI = 34.0
SGL_RX_ANTENNA_GAIN_DBI = 35.0
SGL_SYSTEM_LOSS_DB = 3.0
SGL_ATMOSPHERIC_LOSS_DB = 2.0
SGL_NOISE_FIGURE_DB = 5.0
SGL_MIN_SNR_DB = -5.0
SGL_MAX_DISTANCE_M = 3000000.0
SGL_DOPPLER_COMPENSATION_HZ = 500000.0
SGL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.003
SGL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
SGL_MIN_EFFECTIVE_RATE_BPS = 1e5
SGL_SPECTRAL_EFFICIENCY = 0.60
SGL_RATE_MAPPING_MODE = "discrete"
SGL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
SGL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
)


# Time and output parameters.
NETWORK_RUNNING_STEP_SECOND = 0.05
SAVE_FILE_PATH = (
    "../cases/case3/experiment/output/"
    f"easysatsim_result_{CASE3_OUTPUT_PREFIX}_{CASE3_OUTPUT_TIMESTAMP}.csv"
)
CASE3_EVENT_LOG_FILE_PATH = (
    "cases/case3/experiment/output/"
    f"case3_events_{CASE3_OUTPUT_PREFIX}_{CASE3_OUTPUT_TIMESTAMP}.csv"
)
CASE3_METADATA_FILE_PATH = (
    "cases/case3/experiment/output/"
    f"case3_run_metadata_{CASE3_OUTPUT_PREFIX}_{CASE3_OUTPUT_TIMESTAMP}.json"
)
CASE_RUNNING_TIME_REAL_SECONDS = CASE_SIMULATION_END_TIME


# Fixed computed parameters.
TOTAL_SATELLITE_NUMBER = ORBIT_NUMBER * SATELLITE_NUMBER_PRE_ORBIT
POPULATION_PATH = "../resource/population_matrix.npy"


# Satellite visibility parameters. The user-access behavior consumes COVER_RADIUS.
EARTH_RADIUS_KM = 6371.0
MIN_ELEVATION_ANGLE_DEG = 40.0
MIN_ELEVATION_ANGLE_RAD = np.radians(MIN_ELEVATION_ANGLE_DEG)
COVERAGE_CENTRAL_ANGLE_RAD = (
    np.arccos(
        (
            EARTH_RADIUS_KM
            / (EARTH_RADIUS_KM + ORBIT_HEIGHT)
        )
        * np.cos(MIN_ELEVATION_ANGLE_RAD)
    )
    - MIN_ELEVATION_ANGLE_RAD
)
COVER_RADIUS = EARTH_RADIUS_KM * COVERAGE_CENTRAL_ANGLE_RAD
SATELLITE_CONE_HALF_ANGLE_DEG = (
    90.0
    - MIN_ELEVATION_ANGLE_DEG
    - np.degrees(COVERAGE_CENTRAL_ANGLE_RAD)
)
SATELLITE_CONE_ANGLE = 2.0 * SATELLITE_CONE_HALF_ANGLE_DEG
