import numpy as np

# Constellation parameters
ORBIT_NUMBER = 72
SATELLITE_NUMBER_PRE_ORBIT = 22
ORBIT_INCLINATION = 53
ORBIT_HEIGHT = 550
ORBIT_OMEGA = 5

# Satellite parameters
SATELLITE_CONE_ANGLE = 119.36464665581178
BUFFER_MAX_BYTE = 1e20
# BUFFER_MAX_BYTE = 5e9
SATELLITE_ROUTING_UPDATE_TIME = 5
SATELLITE_NEIGHBOR_UPDATE_TIME = 1
MAX_NEIGHBOR_UPDATE_TIME = 10

# User parameters
USER_NUMBER = 1000
# USER_NUMBER = 3000  # Number of users
USER_LATITUDE_MIN = -50
USER_LATITUDE_MAX = 50
USER_DATA_RATE_MIN = 10
USER_DATA_RATE_MAX = 15
DATA_SCALING = 100
# The user table is updated only when access occurs; this is redundant for now and set for future extensions
USER_ROUTING_UPDATE_TIME = 9999

# Computation parameters
LINK_TRANSMIT_RATE = 1e7
SERVICE_RATE = 1e7
PROCESSING_TIME = 1

# Physical-layer approximation parameters
# LINK_TRANSMIT_RATE is retained as the static compatible rate used when the dynamic model is disabled.
PHYSICAL_LAYER_ENABLE = True
PHYSICAL_LAYER_ENABLE_DOPPLER = True
PHYSICAL_LAYER_ENABLE_DYNAMIC_RATE = True
PHYSICAL_LAYER_UPDATE_INTERVAL = 0.5
PHYSICAL_LAYER_USE_CACHE = True
PHYSICAL_LAYER_DEFAULT_PROCESSING_TIME = PROCESSING_TIME

# ISL physical-layer parameters
ISL_CARRIER_FREQUENCY_HZ = 23e9
ISL_BANDWIDTH_HZ = 250e6
ISL_TX_POWER_DBM = 33.0
ISL_TX_ANTENNA_GAIN_DBI = 35.0
ISL_RX_ANTENNA_GAIN_DBI = 35.0
ISL_SYSTEM_LOSS_DB = 3.0
ISL_ATMOSPHERIC_LOSS_DB = 0.5
ISL_NOISE_FIGURE_DB = 3.0
ISL_MIN_SNR_DB = 0.0
ISL_MAX_DISTANCE_M = 5000000.0
ISL_DOPPLER_COMPENSATION_HZ = 750000.0
ISL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.002
ISL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
ISL_MIN_EFFECTIVE_RATE_BPS = 1e5
ISL_SPECTRAL_EFFICIENCY = 0.65
ISL_RATE_MAPPING_MODE = "discrete"
ISL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
ISL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
    (25.0, 2e8),
)

# SGL physical-layer parameters
SGL_CARRIER_FREQUENCY_HZ = 14e9
SGL_BANDWIDTH_HZ = 100e6
SGL_TX_POWER_DBM = 40.0
SGL_TX_ANTENNA_GAIN_DBI = 32.0
SGL_RX_ANTENNA_GAIN_DBI = 35.0
SGL_SYSTEM_LOSS_DB = 3.0
SGL_ATMOSPHERIC_LOSS_DB = 2.0
SGL_NOISE_FIGURE_DB = 5.0
SGL_MIN_SNR_DB = -2.0
SGL_MAX_DISTANCE_M = 2500000.0
SGL_DOPPLER_COMPENSATION_HZ = 500000.0
SGL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.003
SGL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
SGL_MIN_EFFECTIVE_RATE_BPS = 1e5
SGL_SPECTRAL_EFFICIENCY = 0.60
SGL_RATE_MAPPING_MODE = "discrete"
SGL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
SGL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
)

# Time parameters
# Time step, used to define how long a satellite operates per update. A larger step means the satellite travels farther per update. Normal unit: 0.05 seconds (float)
NETWORK_RUNNING_STEP_SECOND = 0.05

# Save results for each second of operation
SAVE_FILE_PATH = '../output/easysatsim_result.csv'

# Fixed computed parameters
TOTAL_SATELLITE_NUMBER = ORBIT_NUMBER * SATELLITE_NUMBER_PRE_ORBIT
COVER_RADIUS = np.tan(np.radians(SATELLITE_CONE_ANGLE / 2)) * ORBIT_HEIGHT
POPULATION_PATH = "../resource/population_matrix.npy"
