import os
import numpy as np

IDS_MODE = os.environ.get("EASYSATSIM_INTRUSION_IDS", "signature").lower()
OUTPUT_PREFIX = os.environ.get("EASYSATSIM_INTRUSION_OUTPUT_PREFIX", IDS_MODE)


# Constellation parameters
ORBIT_NUMBER = 40
SATELLITE_NUMBER_PRE_ORBIT = 33
ORBIT_INCLINATION = 50.88
ORBIT_HEIGHT = 1325
USER_NUMBER = 1000
CASE_MALICIOUS_USER_NUMBER = 20
CASE_ATTACK_START_TIME = 100
CASE_ATTACK_END_TIME = 500
CASE_SIMULATION_END_TIME = 800

ORBIT_OMEGA = 0


# Satellite parameters
SATELLITE_CONE_ANGLE = 50
BUFFER_MAX_BYTE = 1e20
SATELLITE_ROUTING_UPDATE_TIME = 5
SATELLITE_NEIGHBOR_UPDATE_TIME = 1
MAX_NEIGHBOR_UPDATE_TIME = 10


# User parameters
USER_LATITUDE_MIN = -70
USER_LATITUDE_MAX = 70
USER_DATA_RATE_MIN = 10
USER_DATA_RATE_MAX = 15
DATA_SCALING = 100
USER_ROUTING_UPDATE_TIME = 9999


# Computation parameters
LINK_TRANSMIT_RATE = 1e7
SERVICE_RATE = 1e7
PROCESSING_TIME = 1


# Physical-layer approximation parameters
PHYSICAL_LAYER_ENABLE = True
PHYSICAL_LAYER_ENABLE_DOPPLER = True
PHYSICAL_LAYER_ENABLE_DYNAMIC_RATE = True
PHYSICAL_LAYER_UPDATE_INTERVAL = 0.5
PHYSICAL_LAYER_USE_CACHE = True
PHYSICAL_LAYER_DEFAULT_PROCESSING_TIME = PROCESSING_TIME


# ISL physical-layer parameters
ISL_CARRIER_FREQUENCY_HZ = 23e9
ISL_BANDWIDTH_HZ = 250e6
ISL_TX_POWER_DBM = 33.0
ISL_TX_ANTENNA_GAIN_DBI = 35.0
ISL_RX_ANTENNA_GAIN_DBI = 35.0
ISL_SYSTEM_LOSS_DB = 3.0
ISL_ATMOSPHERIC_LOSS_DB = 0.5
ISL_NOISE_FIGURE_DB = 3.0
ISL_MIN_SNR_DB = 0.0
ISL_MAX_DISTANCE_M = 5000000.0
ISL_DOPPLER_COMPENSATION_HZ = 750000.0
ISL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.002
ISL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
ISL_MIN_EFFECTIVE_RATE_BPS = 1e5
ISL_SPECTRAL_EFFICIENCY = 0.65
ISL_RATE_MAPPING_MODE = "discrete"
ISL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
ISL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
    (25.0, 2e8),
)


# SGL physical-layer parameters
SGL_CARRIER_FREQUENCY_HZ = 14e9
SGL_BANDWIDTH_HZ = 100e6
SGL_TX_POWER_DBM = 40.0
SGL_TX_ANTENNA_GAIN_DBI = 32.0
SGL_RX_ANTENNA_GAIN_DBI = 35.0
SGL_SYSTEM_LOSS_DB = 3.0
SGL_ATMOSPHERIC_LOSS_DB = 2.0
SGL_NOISE_FIGURE_DB = 5.0
SGL_MIN_SNR_DB = -2.0
SGL_MAX_DISTANCE_M = 2500000.0
SGL_DOPPLER_COMPENSATION_HZ = 500000.0
SGL_RESIDUAL_DOPPLER_LOSS_PER_KHZ_DB = 0.003
SGL_STATIC_RATE_BPS = LINK_TRANSMIT_RATE
SGL_MIN_EFFECTIVE_RATE_BPS = 1e5
SGL_SPECTRAL_EFFICIENCY = 0.60
SGL_RATE_MAPPING_MODE = "discrete"
SGL_DROP_LINK_IF_DOPPLER_EXCEEDED = False
SGL_DISCRETE_RATE_TABLE = (
    (-5.0, 1e5),
    (0.0, 1e6),
    (5.0, 5e6),
    (10.0, 1e7),
    (15.0, 5e7),
    (20.0, 1e8),
)


# Time parameters
# The timer adds this value every 0.05 seconds of wall-clock time.
# 0.05 keeps simulation time aligned with wall-clock time.
NETWORK_RUNNING_STEP_SECOND = 0.05


# Case behavior parameters
CASE_RANDOM_SEED = 20260801
CASE_ATTACK_PROBABILITY = 0.7
CASE_MALICIOUS_BEHAVIOR_INTERVAL = 5.0
CASE_ENABLE_NORMAL_PORT22_TRAFFIC = True
CASE_NORMAL_PORT22_START_TIME = CASE_ATTACK_START_TIME
CASE_NORMAL_PORT22_END_TIME = CASE_ATTACK_END_TIME
CASE_NORMAL_PORT22_BEHAVIOR_INTERVAL = 10.0
CASE_NORMAL_PORT22_PROBABILITY = 0.02
CASE_DL_THRESHOLD = 0.9
CASE_DL_MAX_SEQUENCE_LENGTH = 32
CASE_DL_VOCABULARY_SIZE = 512


# Save results for each second of operation.
SAVE_FILE_PATH = f"../cases/case1/experiment/output/{OUTPUT_PREFIX}.csv"


# Fixed computed parameters
TOTAL_SATELLITE_NUMBER = ORBIT_NUMBER * SATELLITE_NUMBER_PRE_ORBIT
COVER_RADIUS = np.tan(np.radians(SATELLITE_CONE_ANGLE / 2)) * ORBIT_HEIGHT
POPULATION_PATH = "../resource/population_matrix.npy"


CASE_RUNNING_TIME_REAL_SECONDS = CASE_SIMULATION_END_TIME
